Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Exclude:
    - "lib/gemsmith/configuration.rb"
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Exclude:
    - "lib/gemsmith/cli.rb"
    - "lib/gemsmith/configuration.rb"
    - "lib/gemsmith/rake/tasks.rb"
