inherit_from: .rubocop_todo.yml

Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
Style/SingleLineBlockParams:
  Enabled: false
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Style/StringLiterals:
  EnforcedStyle: double_quotes
Metrics/LineLength:
  Max: 120
