language: ruby
rvm:
  - 1.9.2
  - 1.9.3
script: bundle exec rspec spec
notifications:
  email: false
  campfire:
    rooms:
      - secure: "b1xAqaauueF59HwFewWwSyMLS7qPQ10k8VjoHBhv+P8xRz3gynMdgTKmAvj6\nNYPO/PeScXOrLxQS5q26CNjfdFeKXlk64+UbT4WEbaLv7uWz+CEZLWIwKaMn\nTjsmbXrX5/e6ha0S5LazmsumCQf9odK3WQlUdqA9+Kavl/uSS5c="
