---
:gem_platform: Gem::Platform::CURRENT
:gem_private_key: /test/private.pem
:gem_public_key: /test/public.pem
:author_name: "Testy Tester"
:author_email: "test@test.com"
:author_url: "https://www.test.com"
:gem_url: "https://www.gem.com"
:company_name: "ACME"
:company_url: "https://www.acme.com"
:github_user: "tester"
:year: 1920
:ruby_version: 1.8.0
:rails_version: 2.3.0
:post_install_message: "Follow @tester on Twitter for more info."
